### ISSUE TITLE
Plowshare is officially on github

### ISSUE THREAD

**Issue by mcrapet** [plowshare/plowshare#2]
https://github.com/mcrapet/plowshare

Please contact me.

**Comment by bullno1** [comment]
Hi, I want to fix solidfiles module but the only module repo on github is legacy and unmaintained. Where should I submit pull request to?

**Comment by mcrapet** [comment]
Your pull requests for modules can be done here:
https://github.com/mcrapet/plowshare-modules-legacy

https://github.com/mcrapet/plowshare
is for "core" only.
